package com.seeyon.ctp.ociporg.po;
// Generated 2019-8-13 14:07:36 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * OrgOcipTempLog generated by hbm2java
 */
public class OrgOcipTempLog implements java.io.Serializable {

    public static final String RESULT_FAUL = "FAIL";

    public static final String RESULT_SUCCESS = "SUCCESS";

    public static final String RESULT_WARN = "WARN";

    /**
     * 
     */
    private static final long serialVersionUID = -6973413927448743123L;
    private Integer id;
    private String msg;
    private String resourceId;
    private String orgId;
    private String name;
    private String type;
    private Date createTime = new Date();
    /**
     * SUCCESS成功 FAIL失败
     */
    private String isOk;

    public OrgOcipTempLog() {}

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getMsg() {
        return this.msg;
    }

    public void setMsg(String msg) {
        this.msg = msg;
    }

    public String getResourceId() {
        return this.resourceId;
    }

    public void setResourceId(String resourceId) {
        this.resourceId = resourceId;
    }

    public String getOrgId() {
        return this.orgId;
    }

    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public String getIsOk() {
        return isOk;
    }

    public void setIsOk(String isOk) {
        this.isOk = isOk;
    }

}
