package com.seeyon.ctp.ociporg.po;
// Generated 2019-8-8 14:17:38 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * OrgUserJoinTemp generated by hbm2java
 */
public class OrgUserJoinTemp implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8730302513950239965L;

	private String id;
	private String orgPlatformUserId;
	private String orgUserLevel;
	private String name;
	private String code;
	private String usedName;
	private Integer sex;
	private Date birthday;
	private Integer nation;
	private String birthPlace;
	private String address;
	private String idCard;
	private String passPort;
	private String driveLicense;
	private Integer eduLevel;
	private Integer marriage;
	private Integer politicalPosition;
	private Integer specialty;
	private String qq;
	private String wechat;
	private String email;
	private String photo;
	private String telNumber;
	private String fixedNumber;
	private String loginName;
	private String password;
	private String hzPassword;
	private String remarks;
	private int isAdmin;
	private Integer sortId;
	private String resourceId;
	private String objectId;
	private Integer isEnable;
	private Integer synState;
	private Integer delFlag;
	private Date createTime;
	private Date updateTime;
	private Short isFlag;

	public OrgUserJoinTemp() {
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getOrgPlatformUserId() {
		return this.orgPlatformUserId;
	}

	public void setOrgPlatformUserId(String orgPlatformUserId) {
		this.orgPlatformUserId = orgPlatformUserId;
	}

	public String getOrgUserLevel() {
		return this.orgUserLevel;
	}

	public void setOrgUserLevel(String orgUserLevel) {
		this.orgUserLevel = orgUserLevel;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getUsedName() {
		return this.usedName;
	}

	public void setUsedName(String usedName) {
		this.usedName = usedName;
	}

	public Integer getSex() {
		return this.sex;
	}

	public void setSex(Integer sex) {
		this.sex = sex;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public Integer getNation() {
		return this.nation;
	}

	public void setNation(Integer nation) {
		this.nation = nation;
	}

	public String getBirthPlace() {
		return this.birthPlace;
	}

	public void setBirthPlace(String birthPlace) {
		this.birthPlace = birthPlace;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getIdCard() {
		return this.idCard;
	}

	public void setIdCard(String idCard) {
		this.idCard = idCard;
	}

	public String getPassPort() {
		return this.passPort;
	}

	public void setPassPort(String passPort) {
		this.passPort = passPort;
	}

	public String getDriveLicense() {
		return this.driveLicense;
	}

	public void setDriveLicense(String driveLicense) {
		this.driveLicense = driveLicense;
	}

	public Integer getEduLevel() {
		return this.eduLevel;
	}

	public void setEduLevel(Integer eduLevel) {
		this.eduLevel = eduLevel;
	}

	public Integer getMarriage() {
		return this.marriage;
	}

	public void setMarriage(Integer marriage) {
		this.marriage = marriage;
	}

	public Integer getPoliticalPosition() {
		return this.politicalPosition;
	}

	public void setPoliticalPosition(Integer politicalPosition) {
		this.politicalPosition = politicalPosition;
	}

	public Integer getSpecialty() {
		return this.specialty;
	}

	public void setSpecialty(Integer specialty) {
		this.specialty = specialty;
	}

	public String getQq() {
		return this.qq;
	}

	public void setQq(String qq) {
		this.qq = qq;
	}

	public String getWechat() {
		return this.wechat;
	}

	public void setWechat(String wechat) {
		this.wechat = wechat;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	public String getTelNumber() {
		return this.telNumber;
	}

	public void setTelNumber(String telNumber) {
		this.telNumber = telNumber;
	}

	public String getFixedNumber() {
		return this.fixedNumber;
	}

	public void setFixedNumber(String fixedNumber) {
		this.fixedNumber = fixedNumber;
	}

	public String getLoginName() {
		return this.loginName;
	}

	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getHzPassword() {
		return this.hzPassword;
	}

	public void setHzPassword(String hzPassword) {
		this.hzPassword = hzPassword;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public int getIsAdmin() {
		return this.isAdmin;
	}

	public void setIsAdmin(int isAdmin) {
		this.isAdmin = isAdmin;
	}

	public Integer getSortId() {
		return this.sortId;
	}

	public void setSortId(Integer sortId) {
		this.sortId = sortId;
	}

	public String getResourceId() {
		return this.resourceId;
	}

	public void setResourceId(String resourceId) {
		this.resourceId = resourceId;
	}

	public String getObjectId() {
		return this.objectId;
	}

	public void setObjectId(String objectId) {
		this.objectId = objectId;
	}

	public Integer getIsEnable() {
		return this.isEnable;
	}

	public void setIsEnable(Integer isEnable) {
		this.isEnable = isEnable;
	}

	public Integer getSynState() {
		return this.synState;
	}

	public void setSynState(Integer synState) {
		this.synState = synState;
	}

	public Integer getDelFlag() {
		return this.delFlag;
	}

	public void setDelFlag(Integer delFlag) {
		this.delFlag = delFlag;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public Short getIsFlag() {
		return this.isFlag;
	}

	public void setIsFlag(Short isFlag) {
		this.isFlag = isFlag;
	}

}
